language: python
python: 2.7
env:
  - TOX_ENV=pypy
  - TOX_ENV=py33
  - TOX_ENV=py27
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libfuse-dev
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
