language: python
python: 2.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libfuse-dev
install:
    - pip install coveralls
    - python setup.py install
script:
    - python setup.py test
    - coveralls
